# This is a basic workflow that is manually triggered

name: Manual workflow

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  pull_request:
    branches: 
    - main
    - master
jobs:
  runs-on: ubuntu-latest
    steps:
    - name: Install dependencies
      run: pip install wheel
    - name: Build package
      run: python setup.py sdist bdist_wheel
    - name: push_to_pipy
      uses: pypa/gh-action-pypi-publish@v1.4.2
      with:
        # PyPI user
        user: __token__
        # Password for your PyPI user or an access token
        password: ${{ secrets.PYPI_API_TOKEN }}
        # The repository URL to use
        repository_url: https://pypi.org/user/jgeof/
        # The target directory for distribution
        packages_dir: dist
        # Check metadata before uploading
        verify_metadata: true
        # Do not fail if a Python package distribution exists in the target package index
          skip_existing: false
        # Show verbose output.
        verbose: true

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "greet"
  greet:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Runs a single command using the runners shell
    - name: Send greeting
      run: echo "Hello ${{ github.event.inputs.name }}"
